# Generated by Django 5.2.5 on 2025-08-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="visit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="visits.visit",
                verbose_name="Visit",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
    ]
