# Generated by Django 5.2.5 on 2025-09-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_created_at_order_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="waiter_full_name",
            field=models.CharField(
                default="njr", max_length=255, verbose_name="Waiter Full Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelled At"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="ordered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ordered At"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="served_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Served At"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("served", "Served"),
                    ("cancelled", "Cancelled"),
                ],
                default="ordered",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
