# Generated by Django 5.2.5 on 2025-09-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("visits", "0004_visit_table_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("CARD", "CARD"),
                            ("CLICK", "CLICK"),
                            ("PAYME", "PAYME"),
                            ("UZUM", "UZUM"),
                            ("PAYLOV", "PAYLOV"),
                            ("PAYNET", "PAYNET"),
                            ("MANUAL", "MANUAL"),
                        ],
                        max_length=50,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Method"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Request Data"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Response Data"
                    ),
                ),
            ],
            options={
                "verbose_name": "PaymentRequestLog",
                "verbose_name_plural": "PaymentRequestLogs",
            },
        ),
        migrations.CreateModel(
            name="BankCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("pan", models.CharField(max_length=32, verbose_name="PAN")),
                (
                    "expire_date",
                    models.CharField(max_length=255, verbose_name="Expire Date"),
                ),
                (
                    "phone_number_mask",
                    models.CharField(max_length=255, verbose_name="Phone Number Mask"),
                ),
                ("cid", models.TextField(verbose_name="Cid")),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Is Confirmed"),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("humo", "Humo"),
                            ("uzcard", "Uzcard"),
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("unionpay", "Unionpay"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Vendor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BankCard",
                "verbose_name_plural": "BankCards",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("CARD", "CARD"),
                            ("CLICK", "CLICK"),
                            ("PAYME", "PAYME"),
                            ("UZUM", "UZUM"),
                            ("PAYLOV", "PAYLOV"),
                            ("PAYNET", "PAYNET"),
                            ("MANUAL", "MANUAL"),
                        ],
                        verbose_name="Provider",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Remote id"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid at"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejected at"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Canceled at"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, null=True, verbose_name="Extra"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="payments.bankcard",
                        verbose_name="Card id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "PaymentTransaction",
                "verbose_name_plural": "PaymentTransactions",
                "db_table": "PaymentTransaction",
                "ordering": ("remote_id",),
            },
        ),
        migrations.AddConstraint(
            model_name="bankcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "pan", "expire_date", "cid"),
                name="unique_bank_card_active",
            ),
        ),
    ]
