# Generated by Django 5.2.5 on 2025-08-22 11:27

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram_link", models.URLField(verbose_name="Instagram Link")),
                ("telegram_link", models.URLField(verbose_name="Telegram Link")),
                ("web_site_link", models.URLField(verbose_name="Web Site Link")),
                (
                    "support_email",
                    models.EmailField(
                        help_text="General support email address",
                        max_length=254,
                        verbose_name="Support Email",
                    ),
                ),
                (
                    "support_telegram_link",
                    models.URLField(verbose_name="Support Telegram Link"),
                ),
                (
                    "support_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        help_text="Information about the company team",
                        verbose_name="About",
                    ),
                ),
                (
                    "about_en",
                    models.TextField(
                        help_text="Information about the company team",
                        null=True,
                        verbose_name="About",
                    ),
                ),
                (
                    "about_ru",
                    models.TextField(
                        help_text="Information about the company team",
                        null=True,
                        verbose_name="About",
                    ),
                ),
                (
                    "about_uz",
                    models.TextField(
                        help_text="Information about the company team",
                        null=True,
                        verbose_name="About",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profile",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("alpha_2", models.CharField(max_length=2, unique=True)),
                ("alpha_3", models.CharField(max_length=3, unique=True)),
                ("numeric", models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backoffice_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the backoffice",
                        null=True,
                        verbose_name="Backoffice URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.FileField(upload_to="stories/", verbose_name="Media")),
                ("link", models.URLField(verbose_name="Link")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="UserSearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Text")),
            ],
            options={
                "verbose_name": "User Search History",
                "verbose_name_plural": "User Search Histories",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserVenueFavourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Venue Favourite",
                "verbose_name_plural": "User Venue Favourites",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=16, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="common.country",
                    ),
                ),
            ],
        ),
    ]
