# Generated by Django 5.2.5 on 2025-08-27 07:30

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_country_created_at_country_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "message_id",
                    models.CharField(max_length=255, verbose_name="Message ID"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is sent")),
                ("sent_at", models.DateTimeField(null=True, verbose_name="Sent at")),
                (
                    "is_delivered",
                    models.BooleanField(default=False, verbose_name="Is delivered"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(null=True, verbose_name="Delivered at"),
                ),
                (
                    "response_log",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Response log"
                    ),
                ),
                (
                    "callback_log",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Callback log"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("STORED", "Stored"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="WAITING",
                        max_length=20,
                        verbose_name="Carrier status",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
