# Generated by Django 5.2.5 on 2025-08-29 19:17

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_alter_usersearchhistory_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="background_image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="stories/background_images/",
                verbose_name="Background Image",
            ),
        ),
    ]
