# Generated by Django 5.2.5 on 2025-08-30 06:56

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_story_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="icon",
            field=versatileimagefield.fields.VersatileImageField(
                default="facilities/icons/wifi.png",
                upload_to="facilities/icons/",
                verbose_name="Icon",
            ),
            preserve_default=False,
        ),
    ]
