# Generated by Django 5.2.5 on 2025-08-30 10:54

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_facility_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="icon",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="facilities/icons/",
                verbose_name="Icon",
            ),
        ),
    ]
