# Generated by Django 5.2.5 on 2025-08-31 11:48

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_alter_facility_icon"),
        ("venues", "0013_alter_venuecategory_icon_alter_venuecategory_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "background_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to="stories/background_images/",
                        verbose_name="Background Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Story Group",
                "verbose_name_plural": "Story Groups",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="StoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("media", models.FileField(upload_to="stories/", verbose_name="Media")),
                ("description", models.TextField(blank=True, verbose_name="Text")),
                ("link", models.URLField(blank=True, verbose_name="Link")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "story_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_items",
                        to="common.storygroup",
                        verbose_name="Story Group",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="venues.venue",
                        verbose_name="Venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Item",
                "verbose_name_plural": "Story Items",
                "ordering": ("story_group", "order", "created_at"),
            },
        ),
        migrations.DeleteModel(
            name="Story",
        ),
    ]
