# Generated by Django 5.2.5 on 2025-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_storygroup_storyitem_delete_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="quick_access",
            field=models.BooleanField(default=False, verbose_name="Quick Access"),
        ),
    ]
