# Generated by Django 5.2.5 on 2025-09-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_facility_quick_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="about_zh_cn",
            field=models.TextField(
                help_text="Information about the company team",
                null=True,
                verbose_name="About",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="facility",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="facility",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="facility",
            name="title_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="storygroup",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="storygroup",
            name="title_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="storygroup",
            name="title_uz",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="storygroup",
            name="title_zh_cn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="storyitem",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="storyitem",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="storyitem",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="storyitem",
            name="description_zh_cn",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
