# Generated by Django 5.2.5 on 2025-09-03 19:35

from django.db import migrations

def populate_translation_fields(apps, schema_editor):
    CompanyProfile = apps.get_model('common', 'CompanyProfile')
    Facility = apps.get_model('common', 'Facility')
    Tag = apps.get_model('common', 'Tag')
    StoryGroup = apps.get_model('common', 'StoryGroup')
    StoryItem = apps.get_model('common', 'StoryItem')

    # Populate CompanyProfile about field
    for profile in CompanyProfile.objects.all():
        if profile.about:
            profile.about_en = profile.about
            profile.about_ru = profile.about
            profile.about_uz = profile.about
            profile.about_zh_cn = profile.about
            profile.save(update_fields=['about_en', 'about_ru', 'about_uz', 'about_zh_cn'])

    # Populate Facility title field
    for facility in Facility.objects.all():
        if facility.title:
            facility.title_en = facility.title
            facility.title_ru = facility.title
            facility.title_uz = facility.title
            facility.title_zh_cn = facility.title
            facility.save(update_fields=['title_en', 'title_ru', 'title_uz', 'title_zh_cn'])

    # Populate Tag title field
    for tag in Tag.objects.all():
        if tag.title:
            tag.title_en = tag.title
            tag.title_ru = tag.title
            tag.title_uz = tag.title
            tag.title_zh_cn = tag.title
            tag.save(update_fields=['title_en', 'title_ru', 'title_uz', 'title_zh_cn'])

    # Populate StoryGroup title field
    for story_group in StoryGroup.objects.all():
        if story_group.title:
            story_group.title_en = story_group.title
            story_group.title_ru = story_group.title
            story_group.title_uz = story_group.title
            story_group.title_zh_cn = story_group.title
            story_group.save(update_fields=['title_en', 'title_ru', 'title_uz', 'title_zh_cn'])

    # Populate StoryItem description field
    for story_item in StoryItem.objects.all():
        if story_item.description:
            story_item.description_en = story_item.description
            story_item.description_ru = story_item.description
            story_item.description_uz = story_item.description
            story_item.description_zh_cn = story_item.description
            story_item.save(update_fields=['description_en', 'description_ru', 'description_uz', 'description_zh_cn'])


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_companyprofile_about_zh_cn_facility_title_en_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_translation_fields),
    ]
