# Generated by Django 5.2.4 on 2025-08-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Username"
            ),
        ),
    ]
