# Generated by Django 5.2.5 on 2025-08-27 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 8, 27, 7, 36, 58, 857697, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date of Birth",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("host", "Host")],
                default="user",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
