# Generated by Django 5.2.5 on 2025-09-01 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_date_of_birth_alter_user_role"),
        ("venues", "0013_alter_venuecategory_icon_alter_venuecategory_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="venues.venue",
            ),
        ),
    ]
