# Generated by Django 5.2.5 on 2025-09-03 18:45

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=64, region=None, unique=True, verbose_name="Phone number"
            ),
        ),
    ]
