# Generated by Django 5.2.5 on 2025-09-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("ru", "Russian"),
                    ("uz", "Uzbek"),
                    ("zh-cn", "Chinese"),
                ],
                default="uz",
                max_length=6,
                verbose_name="Language",
            ),
        ),
    ]
