# Generated by Django 5.2.5 on 2025-08-22 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "logo",
                    models.ImageField(
                        upload_to="companies/logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="VenueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "icon",
                    models.ImageField(
                        upload_to="venue/categories/", verbose_name="Icon"
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Venue Category",
                "verbose_name_plural": "Venue Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VenueZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "photo_view",
                    models.ImageField(
                        upload_to="venue/zones/", verbose_name="Photo View"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue Zone",
                "verbose_name_plural": "Venue Zones",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="Rating"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venues.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True, to="common.facility", verbose_name="Facilities"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="common.tag", verbose_name="Tags"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, to="venues.venuecategory", verbose_name="Categories"
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
            },
        ),
        migrations.CreateModel(
            name="VenueImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                (
                    "image",
                    models.ImageField(upload_to="venue/images/", verbose_name="Image"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Is Main")),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="venues.venue",
                        verbose_name="Venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue Image",
                "verbose_name_plural": "Venue Images",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="venue",
            name="background_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background_for",
                to="venues.venueimage",
                verbose_name="Background Image",
            ),
        ),
        migrations.CreateModel(
            name="VenueReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Rating"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is Approved"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue Review",
                "verbose_name_plural": "Venue Reviews",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="VenueSocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "social_type",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("telegram", "Telegram"),
                            ("twitter", "Twitter"),
                            ("tiktok", "TikTok"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Social Type",
                    ),
                ),
                ("link", models.URLField(verbose_name="Link")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="venues.venue",
                        verbose_name="Venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue Social Media",
                "verbose_name_plural": "Venue Social Media",
            },
        ),
        migrations.CreateModel(
            name="VenueWorkingHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("opening_time", models.TimeField(verbose_name="Opening Time")),
                ("closing_time", models.TimeField(verbose_name="Closing Time")),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=10,
                        verbose_name="Weekday",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venues.venue",
                        verbose_name="Venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue Working Hour",
                "verbose_name_plural": "Venue Working Hours",
                "ordering": ["venue", "weekday", "opening_time"],
            },
        ),
    ]
