# Generated by Django 5.2.5 on 2025-08-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=255,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=255,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
        migrations.AddField(
            model_name="venuecategory",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=255,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
        migrations.AddField(
            model_name="venueimage",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=255,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
        migrations.AddField(
            model_name="venuereview",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=255,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
    ]
