# Generated by Django 5.2.5 on 2025-08-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_company_parsing_id_venue_parsing_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=500,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=500,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
        migrations.AlterField(
            model_name="venuecategory",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=500,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
        migrations.AlterField(
            model_name="venueimage",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=500,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
        migrations.AlterField(
            model_name="venuereview",
            name="parsing_id",
            field=models.CharField(
                blank=True,
                help_text="ID from parsing system",
                max_length=500,
                null=True,
                verbose_name="Parsing ID",
            ),
        ),
    ]
