# Generated by Django 5.2.5 on 2025-08-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0003_alter_company_parsing_id_alter_venue_parsing_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuecategory",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="External ID"
            ),
        ),
        migrations.AddField(
            model_name="venuezone",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="venues.venue",
                verbose_name="Venue",
            ),
            preserve_default=False,
        ),
    ]
