# Generated by Django 5.2.5 on 2025-08-27 21:05

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0004_venuecategory_external_id_venuezone_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="companies/logos/", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="venuecategory",
            name="icon",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="venue/categories/", verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="venueimage",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="venue/images/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="venuezone",
            name="photo_view",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="venue/zones/", verbose_name="Photo View"
            ),
        ),
    ]
