# Generated by Django 5.2.5 on 2025-08-28 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0005_alter_company_logo_alter_venuecategory_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venue",
            old_name="category",
            new_name="categories",
        ),
    ]
