# Generated by Django 5.2.5 on 2025-08-28 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0006_rename_category_venue_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuereview",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="venues.venue",
                verbose_name="Venue",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venuereview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
