# Generated by Django 5.2.5 on 2025-08-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0007_venuereview_venue_alter_venuereview_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venueworkinghour",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="venues.venue",
                verbose_name="Venue",
            ),
        ),
    ]
