# Generated by Django 5.2.5 on 2025-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0008_alter_venueworkinghour_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuecategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("venue_type", "Venue Type"),
                    ("cuisine_type", "Cuisine Type"),
                ],
                default="venue_type",
                max_length=50,
                verbose_name="Category Type",
            ),
        ),
    ]
