# Generated by Django 5.2.5 on 2025-08-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0009_venuecategory_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuecategory",
            name="recommended",
            field=models.BooleanField(default=False, verbose_name="Recommended"),
        ),
    ]
