# Generated by Django 5.2.5 on 2025-08-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0010_venuecategory_recommended"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="venues",
                to="venues.venuecategory",
                verbose_name="Categories",
            ),
        ),
    ]
