# Generated by Django 5.2.5 on 2025-08-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0011_venue_is_active_alter_venue_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuesocialmedia",
            name="title",
            field=models.CharField(
                default="Tantana", max_length=255, verbose_name="Title"
            ),
            preserve_default=False,
        ),
    ]
