# Generated by Django 5.2.5 on 2025-08-30 10:38

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0012_venuesocialmedia_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuecategory",
            name="icon",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="venue/categories/",
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="venuecategory",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
    ]
