# Generated by Django 5.2.5 on 2025-09-01 16:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0013_alter_venuecategory_icon_alter_venuecategory_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=15,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
