# Generated by Django 5.2.5 on 2025-09-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0014_venue_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="company",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="company",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="company",
            name="name_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="venue",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="venue",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="venue",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="venue",
            name="description_zh_cn",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="venue",
            name="location_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="venue",
            name="location_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="venue",
            name="location_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="venue",
            name="location_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="venue",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="venue",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="venue",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="venue",
            name="name_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="venuecategory",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="venuecategory",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="venuecategory",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="venuecategory",
            name="title_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="venuezone",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="venuezone",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="venuezone",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="venuezone",
            name="name_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
    ]
