# Generated by Django 5.2.5 on 2025-09-03 19:35

from django.db import migrations


def populate_translation_fields(apps, schema_editor):
    Company = apps.get_model('venues', 'Company')
    VenueCategory = apps.get_model('venues', 'VenueCategory')
    Venue = apps.get_model('venues', 'Venue')
    VenueZone = apps.get_model('venues', 'VenueZone')

    # Populate Company name field
    for company in Company.objects.all():
        if company.name:
            company.name_en = company.name
            company.name_ru = company.name
            company.name_uz = company.name
            company.name_zh_cn = company.name
            company.save(update_fields=['name_en', 'name_ru', 'name_uz', 'name_zh_cn'])

    # Populate VenueCategory title field
    for category in VenueCategory.objects.all():
        if category.title:
            category.title_en = category.title
            category.title_ru = category.title
            category.title_uz = category.title
            category.title_zh_cn = category.title
            category.save(update_fields=['title_en', 'title_ru', 'title_uz', 'title_zh_cn'])

    # Populate Venue name and description fields
    for venue in Venue.objects.all():
        if venue.name:
            venue.name_en = venue.name
            venue.name_ru = venue.name
            venue.name_uz = venue.name
            venue.name_zh_cn = venue.name
            venue.save(update_fields=['name_en', 'name_ru', 'name_uz', 'name_zh_cn'])
        
        if venue.description:
            venue.description_en = venue.description
            venue.description_ru = venue.description
            venue.description_uz = venue.description
            venue.description_zh_cn = venue.description
            venue.save(update_fields=['description_en', 'description_ru', 'description_uz', 'description_zh_cn'])
        
        if venue.location:
            venue.location_en = venue.location
            venue.location_ru = venue.location
            venue.location_uz = venue.location
            venue.location_zh_cn = venue.location
            venue.save(update_fields=['location_en', 'location_ru', 'location_uz', 'location_zh_cn'])

    # Populate VenueZone name field
    for zone in VenueZone.objects.all():
        if zone.name:
            zone.name_en = zone.name
            zone.name_ru = zone.name
            zone.name_uz = zone.name
            zone.name_zh_cn = zone.name
            zone.save(update_fields=['name_en', 'name_ru', 'name_uz', 'name_zh_cn'])

class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0015_company_name_en_company_name_ru_company_name_uz_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_translation_fields),
    ]
