# Generated by Django 5.2.5 on 2025-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0016_auto_20250903_1935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuesocialmedia",
            name="social_type",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("telegram", "Telegram"),
                    ("twitter", "Twitter"),
                    ("tiktok", "TikTok"),
                    ("whatsapp", "WhatsApp"),
                    ("website", "Website"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Social Type",
            ),
        ),
    ]
