# Generated by Django 5.2.5 on 2025-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0017_alter_venuesocialmedia_social_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="iiko_api_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="IIKO API Token"
            ),
        ),
    ]
