# Generated by Django 5.2.5 on 2025-09-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="waiter_full_name",
        ),
        migrations.AlterField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                    ("payment", "Payment"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="booked",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
