# Generated by Django 5.2.5 on 2025-09-01 13:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0013_alter_venuecategory_icon_alter_venuecategory_order"),
        ("visits", "0002_remove_visit_waiter_full_name_alter_visit_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Cancel Reason"),
        ),
        migrations.AddField(
            model_name="visit",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelled At"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="created_by",
            field=models.CharField(
                choices=[("user", "User"), ("host", "Host")],
                default="user",
                max_length=20,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_visits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Host",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="user_full_name",
            field=models.CharField(
                default="njr", max_length=255, verbose_name="User Full Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visit",
            name="user_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+998990004740",
                max_length=128,
                region=None,
                verbose_name="User Phone Number",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="venues.venue",
                verbose_name="Venue",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="venues.venuezone",
                verbose_name="Zone",
            ),
        ),
    ]
