# Generated by Django 5.2.5 on 2025-09-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0003_visit_cancel_reason_visit_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="table_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Table Number"
            ),
        ),
    ]
