name: run_tests
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: SOME_SECRET_KEY
      DEBUG: FALSE
      DJANGO_SETTINGS_MODULE: core.settings.develop

      DATABASE: postgres
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: tantana
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/tantana

      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379

      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_DB: 0

      # RECAPTCHA
      SENTRY_BOT_TOKEN: SENTRY_BOT_TOKEN
      SENTRY_CHAT_ID: SENTRY_CHAT_ID
      SENTRY_THREAD_ID: SENTRY_THREAD_ID


      # GOOGLE PLACES
      GOOGLE_PLACES_API_KEY: GOOGLE_PLACES_API_KEY
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements/base.txt
      - run: pip install -r requirements/develop.txt
      - run: python manage.py test
