# Generated by Django 5.2.5 on 2025-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomFCMDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive devices will not be sent notifications",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique device identifier",
                        max_length=255,
                        null=True,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "registration_id",
                    models.TextField(unique=True, verbose_name="Registration token"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ios", "ios"),
                            ("android", "android"),
                            ("web", "web"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM device",
                "verbose_name_plural": "FCM devices",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                ("body_text", models.TextField(verbose_name="Body (Plain Text)")),
                (
                    "body_text_en",
                    models.TextField(null=True, verbose_name="Body (Plain Text)"),
                ),
                (
                    "body_text_ru",
                    models.TextField(null=True, verbose_name="Body (Plain Text)"),
                ),
                (
                    "body_text_uz",
                    models.TextField(null=True, verbose_name="Body (Plain Text)"),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
                ),
                (
                    "body_html_en",
                    models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
                ),
                (
                    "body_html_ru",
                    models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
                ),
                (
                    "body_html_uz",
                    models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
                ),
                (
                    "is_for_everyone",
                    models.BooleanField(default=False, verbose_name="Is for everyone"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("booking_created", "Booking Created"),
                            ("booking_reminder", "Booking Reminder"),
                            ("booking_updated", "Booking Updated"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("table_ready", "Table Ready"),
                            ("bill_opened", "Bill Opened"),
                            ("bill_updated", "Bill Updated"),
                            ("bill_closed", "Bill Closed"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                        ],
                        max_length=24,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_process", "In Process"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "only_push",
                    models.BooleanField(default=False, verbose_name="Only Push"),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Data")),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("booking_created", "Booking Created"),
                            ("booking_reminder", "Booking Reminder"),
                            ("booking_updated", "Booking Updated"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("table_ready", "Table Ready"),
                            ("bill_opened", "Bill Opened"),
                            ("bill_updated", "Bill Updated"),
                            ("bill_closed", "Bill Closed"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                ("body_text", models.TextField(verbose_name="Body (Plain Text)")),
                (
                    "body_text_en",
                    models.TextField(null=True, verbose_name="Body (Plain Text)"),
                ),
                (
                    "body_text_ru",
                    models.TextField(null=True, verbose_name="Body (Plain Text)"),
                ),
                (
                    "body_text_uz",
                    models.TextField(null=True, verbose_name="Body (Plain Text)"),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
                ),
                (
                    "body_html_en",
                    models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
                ),
                (
                    "body_html_ru",
                    models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
                ),
                (
                    "body_html_uz",
                    models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
                ),
            ],
            options={
                "verbose_name": "Notification template",
                "verbose_name_plural": "Notification templates",
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is sent")),
                ("is_read", models.BooleanField(default=False, verbose_name="Is read")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Data")),
            ],
            options={
                "verbose_name": "UserNotification",
                "verbose_name_plural": "UserNotifications",
                "ordering": ("-created_at",),
            },
        ),
    ]
