# Generated by Django 5.2.5 on 2025-09-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="body_html_zh_cn",
            field=models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
        ),
        migrations.AddField(
            model_name="notification",
            name="body_text_zh_cn",
            field=models.TextField(null=True, verbose_name="Body (Plain Text)"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="body_html_zh_cn",
            field=models.TextField(blank=True, null=True, verbose_name="Body (HTML)"),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="body_text_zh_cn",
            field=models.TextField(null=True, verbose_name="Body (Plain Text)"),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="title_zh_cn",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
